/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burgerrushuas;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Salsabila Ramadhania
 */
public class statistikGame extends javax.swing.JFrame {
    Koneksi kon;

    private String usernameLogin;
    private int currentScore;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(statistikGame.class.getName());

    /**
     * Creates new form statistikGame
     */
    public statistikGame() {
        initComponents();
        
        kon = new Koneksi();

        usernameLogin = "Asya";
        currentScore = 8500;

        lblUsernameLogin.setText(usernameLogin);
        lblCurrentScore.setText(String.valueOf(currentScore));

        tampilkanStatistikUser();
    }
    
    public statistikGame(String usernameLogin, int currentScore) {
        initComponents();

        kon = new Koneksi();

        this.usernameLogin = usernameLogin;
        this.currentScore = currentScore;

        lblUsernameLogin.setText(usernameLogin);
        lblCurrentScore.setText(String.valueOf(currentScore));

        tampilkanStatistikUser();
    }
    
    private void tampilkanStatistikUser() {
        String query_statistik = "SELECT highscore, current_score, total_order, order_selesai, order_gagal, total_bermain "
                + "FROM scores WHERE username = '" + usernameLogin + "'";

        try {
            Statement st = kon.con.createStatement();
            ResultSet rs = st.executeQuery(query_statistik);

            if (rs.next()) {
                int highscore = rs.getInt("highscore");
                int currentScoreDB = rs.getInt("current_score");
                int totalOrder = rs.getInt("total_order");
                int orderSelesai = rs.getInt("order_selesai");
                int orderGagal = rs.getInt("order_gagal");
                int totalBermain = rs.getInt("total_bermain");

                lblCurrentScore.setText(String.valueOf(currentScoreDB));
                lblHighScoreValue.setText(String.valueOf(highscore));
                lblTotalOrderValue.setText(String.valueOf(totalOrder));
                lblOrderSelesaiValue.setText(String.valueOf(orderSelesai));
                lblOrderGagalValue.setText(String.valueOf(orderGagal));
                lblTotalBermainValue.setText(String.valueOf(totalBermain));

            } else {
                JOptionPane.showMessageDialog(null, "Data statistik user tidak ditemukan");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Gagal menampilkan statistik!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStatistik = new javax.swing.JLabel();
        panelInfoUser = new javax.swing.JPanel();
        lblLoggedIn = new javax.swing.JLabel();
        lblUsernameLogin = new javax.swing.JLabel();
        lblCurrentScoreText = new javax.swing.JLabel();
        lblCurrentScore = new javax.swing.JLabel();
        separatorInfoUser = new javax.swing.JSeparator();
        lblAvatarIcon = new javax.swing.JLabel();
        lblTrophyIcon = new javax.swing.JLabel();
        panelStatistik = new javax.swing.JPanel();
        lblStatistikHeader = new javax.swing.JLabel();
        lblHighScore = new javax.swing.JLabel();
        lblOrderSelesai = new javax.swing.JLabel();
        lblOrderSelesaiValue = new javax.swing.JLabel();
        lblOrderGagal = new javax.swing.JLabel();
        lblTotalOrderValue = new javax.swing.JLabel();
        lblTotalOrder = new javax.swing.JLabel();
        lblHighScoreValue = new javax.swing.JLabel();
        line1 = new javax.swing.JSeparator();
        line2 = new javax.swing.JSeparator();
        line3 = new javax.swing.JSeparator();
        lblOrderGagalValue = new javax.swing.JLabel();
        lblTotalBermain = new javax.swing.JLabel();
        line4 = new javax.swing.JSeparator();
        lblTotalBermainValue = new javax.swing.JLabel();
        btnLeaderboard = new javax.swing.JButton();
        lblMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 44, 24));

        lblStatistik.setFont(new java.awt.Font("Pixelify Sans", 1, 32)); // NOI18N
        lblStatistik.setForeground(new java.awt.Color(255, 255, 255));
        lblStatistik.setText("STATISTIK GAME");

        panelInfoUser.setBackground(new java.awt.Color(248, 220, 163));
        panelInfoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 175, 96), 2));

        lblLoggedIn.setFont(new java.awt.Font("Pixelify Sans", 1, 16)); // NOI18N
        lblLoggedIn.setForeground(new java.awt.Color(43, 27, 18));
        lblLoggedIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoggedIn.setText("Logged in as:");

        lblUsernameLogin.setFont(new java.awt.Font("Pixelify Sans", 1, 28)); // NOI18N
        lblUsernameLogin.setForeground(new java.awt.Color(43, 27, 18));
        lblUsernameLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsernameLogin.setText("Asya");

        lblCurrentScoreText.setFont(new java.awt.Font("Pixelify Sans", 1, 16)); // NOI18N
        lblCurrentScoreText.setForeground(new java.awt.Color(43, 27, 18));
        lblCurrentScoreText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCurrentScoreText.setText("Current Score");

        lblCurrentScore.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        lblCurrentScore.setForeground(new java.awt.Color(43, 27, 18));
        lblCurrentScore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCurrentScore.setText("8500");

        separatorInfoUser.setBackground(new java.awt.Color(120, 85, 45));
        separatorInfoUser.setForeground(new java.awt.Color(120, 85, 45));
        separatorInfoUser.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAvatarIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/avatar.png"))); // NOI18N

        lblTrophyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/trophy.png"))); // NOI18N

        javax.swing.GroupLayout panelInfoUserLayout = new javax.swing.GroupLayout(panelInfoUser);
        panelInfoUser.setLayout(panelInfoUserLayout);
        panelInfoUserLayout.setHorizontalGroup(
            panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoUserLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblAvatarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoggedIn)
                    .addComponent(lblUsernameLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(separatorInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblTrophyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentScoreText)
                    .addGroup(panelInfoUserLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblCurrentScore)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelInfoUserLayout.setVerticalGroup(
            panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoUserLayout.createSequentialGroup()
                .addGroup(panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInfoUserLayout.createSequentialGroup()
                                .addComponent(lblCurrentScoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCurrentScore))
                            .addGroup(panelInfoUserLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAvatarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelInfoUserLayout.createSequentialGroup()
                                        .addComponent(lblLoggedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUsernameLogin))))
                            .addComponent(separatorInfoUser)))
                    .addGroup(panelInfoUserLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblTrophyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelStatistik.setBackground(new java.awt.Color(248, 220, 163));
        panelStatistik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 175, 96), 3));

        lblStatistikHeader.setBackground(new java.awt.Color(230, 100, 28));
        lblStatistikHeader.setFont(new java.awt.Font("Pixelify Sans", 1, 20)); // NOI18N
        lblStatistikHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblStatistikHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatistikHeader.setText("STATISTIK GAME");
        lblStatistikHeader.setOpaque(true);

        lblHighScore.setFont(new java.awt.Font("Pixelify Sans", 1, 16)); // NOI18N
        lblHighScore.setForeground(new java.awt.Color(43, 27, 18));
        lblHighScore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHighScore.setText("High Score");

        lblOrderSelesai.setFont(new java.awt.Font("Pixelify Sans", 1, 16)); // NOI18N
        lblOrderSelesai.setForeground(new java.awt.Color(43, 27, 18));
        lblOrderSelesai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOrderSelesai.setText("Order Selesai");

        lblOrderSelesaiValue.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lblOrderSelesaiValue.setForeground(new java.awt.Color(43, 27, 18));
        lblOrderSelesaiValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOrderSelesaiValue.setText("25");

        lblOrderGagal.setFont(new java.awt.Font("Pixelify Sans", 1, 16)); // NOI18N
        lblOrderGagal.setForeground(new java.awt.Color(43, 27, 18));
        lblOrderGagal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOrderGagal.setText("Order Gagal");

        lblTotalOrderValue.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lblTotalOrderValue.setForeground(new java.awt.Color(43, 27, 18));
        lblTotalOrderValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalOrderValue.setText("30");

        lblTotalOrder.setFont(new java.awt.Font("Pixelify Sans", 1, 16)); // NOI18N
        lblTotalOrder.setForeground(new java.awt.Color(43, 27, 18));
        lblTotalOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalOrder.setText("Total Order");

        lblHighScoreValue.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lblHighScoreValue.setForeground(new java.awt.Color(43, 27, 18));
        lblHighScoreValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHighScoreValue.setText("999999");

        line1.setBackground(new java.awt.Color(193, 151, 90));
        line1.setOpaque(true);

        line2.setBackground(new java.awt.Color(193, 151, 90));
        line2.setOpaque(true);

        line3.setBackground(new java.awt.Color(193, 151, 90));
        line3.setOpaque(true);

        lblOrderGagalValue.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lblOrderGagalValue.setForeground(new java.awt.Color(43, 27, 18));
        lblOrderGagalValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOrderGagalValue.setText("5");

        lblTotalBermain.setFont(new java.awt.Font("Pixelify Sans", 1, 16)); // NOI18N
        lblTotalBermain.setForeground(new java.awt.Color(43, 27, 18));
        lblTotalBermain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalBermain.setText("Total Bermain");

        line4.setBackground(new java.awt.Color(193, 151, 90));
        line4.setOpaque(true);

        lblTotalBermainValue.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        lblTotalBermainValue.setForeground(new java.awt.Color(43, 27, 18));
        lblTotalBermainValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalBermainValue.setText("12");

        javax.swing.GroupLayout panelStatistikLayout = new javax.swing.GroupLayout(panelStatistik);
        panelStatistik.setLayout(panelStatistikLayout);
        panelStatistikLayout.setHorizontalGroup(
            panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatistikLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lblStatistikHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatistikLayout.createSequentialGroup()
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelStatistikLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHighScoreValue))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelStatistikLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatistikLayout.createSequentialGroup()
                                .addComponent(lblTotalOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalOrderValue))
                            .addGroup(panelStatistikLayout.createSequentialGroup()
                                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatistikLayout.createSequentialGroup()
                                        .addComponent(lblOrderSelesai)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOrderSelesaiValue))
                                    .addComponent(line2)
                                    .addComponent(line3)
                                    .addGroup(panelStatistikLayout.createSequentialGroup()
                                        .addComponent(lblOrderGagal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOrderGagalValue))
                                    .addComponent(line4)
                                    .addGroup(panelStatistikLayout.createSequentialGroup()
                                        .addComponent(lblHighScore)
                                        .addGap(450, 450, 450))
                                    .addGroup(panelStatistikLayout.createSequentialGroup()
                                        .addComponent(lblTotalBermain)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotalBermainValue)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );
        panelStatistikLayout.setVerticalGroup(
            panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatistikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatistikHeader)
                .addGap(18, 18, 18)
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStatistikLayout.createSequentialGroup()
                        .addComponent(lblHighScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHighScoreValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalOrderValue)
                    .addComponent(lblTotalOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderSelesai)
                    .addComponent(lblOrderSelesaiValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderGagal)
                    .addComponent(lblOrderGagalValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBermain)
                    .addComponent(lblTotalBermainValue))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnLeaderboard.setBackground(new java.awt.Color(59, 130, 246));
        btnLeaderboard.setFont(new java.awt.Font("Pixelify Sans", 1, 20)); // NOI18N
        btnLeaderboard.setForeground(new java.awt.Color(255, 255, 255));
        btnLeaderboard.setText("LEADERBOARD");
        btnLeaderboard.setBorderPainted(false);
        btnLeaderboard.setFocusPainted(false);
        btnLeaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLeaderboardMouseClicked(evt);
            }
        });
        btnLeaderboard.addActionListener(this::btnLeaderboardActionPerformed);

        lblMainMenu.setBackground(new java.awt.Color(242, 201, 76));
        lblMainMenu.setFont(new java.awt.Font("Pixelify Sans", 1, 20)); // NOI18N
        lblMainMenu.setForeground(new java.awt.Color(43, 27, 18));
        lblMainMenu.setText("Main Menu");
        lblMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblStatistik))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnLeaderboard)
                        .addGap(131, 131, 131)
                        .addComponent(lblMainMenu)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblStatistik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeaderboard)
                    .addComponent(lblMainMenu))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaderboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeaderboardActionPerformed

    private void btnLeaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeaderboardMouseClicked
        // TODO add your handling code here:
        leaderboard form_leaderboard = new leaderboard(usernameLogin);
        form_leaderboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLeaderboardMouseClicked

    private void lblMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMenuMouseClicked
        // TODO add your handling code here:
//        MainMenuFrame form_menu = new MainMenuFrame();
//        form_menu.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_lblMainMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new statistikGame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeaderboard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatarIcon;
    private javax.swing.JLabel lblCurrentScore;
    private javax.swing.JLabel lblCurrentScoreText;
    private javax.swing.JLabel lblHighScore;
    private javax.swing.JLabel lblHighScoreValue;
    private javax.swing.JLabel lblLoggedIn;
    private javax.swing.JButton lblMainMenu;
    private javax.swing.JLabel lblOrderGagal;
    private javax.swing.JLabel lblOrderGagalValue;
    private javax.swing.JLabel lblOrderSelesai;
    private javax.swing.JLabel lblOrderSelesaiValue;
    private javax.swing.JLabel lblStatistik;
    private javax.swing.JLabel lblStatistikHeader;
    private javax.swing.JLabel lblTotalBermain;
    private javax.swing.JLabel lblTotalBermainValue;
    private javax.swing.JLabel lblTotalOrder;
    private javax.swing.JLabel lblTotalOrderValue;
    private javax.swing.JLabel lblTrophyIcon;
    private javax.swing.JLabel lblUsernameLogin;
    private javax.swing.JSeparator line1;
    private javax.swing.JSeparator line2;
    private javax.swing.JSeparator line3;
    private javax.swing.JSeparator line4;
    private javax.swing.JPanel panelInfoUser;
    private javax.swing.JPanel panelStatistik;
    private javax.swing.JSeparator separatorInfoUser;
    // End of variables declaration//GEN-END:variables
}
