/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableCellRenderer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author hp
 */
public class InventoryShopFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryShopFrame.class.getName());
    
    int saldo = 500;
    

    /**
     * Creates new form InventoryShopFrame
     */
    public InventoryShopFrame() {
    initComponents();

    //LBsaldo.setText("Saldo : " + saldo);
    loadSaldo();
    loadBahan();

    // HEADER TABEL
    DefaultTableCellRenderer headerRenderer =
            new DefaultTableCellRenderer();

    headerRenderer.setHorizontalAlignment(
            javax.swing.SwingConstants.CENTER);

    headerRenderer.setBackground(
            new Color(107, 45, 15)); // coklat tua

    headerRenderer.setForeground(
            Color.WHITE);

    headerRenderer.setFont(
            new Font("Pixelify Sans", Font.BOLD, 18));

    for (int i = 0; i < TableBahan.getColumnModel().getColumnCount(); i++) {
        TableBahan.getColumnModel()
                .getColumn(i)
                .setHeaderRenderer(headerRenderer);
    }

    // TINGGI HEADER
    TableBahan.getTableHeader().setPreferredSize(
            new java.awt.Dimension(0, 25));

    // FONT ISI TABEL
    TableBahan.setFont(
            new Font("Pixelify Sans", Font.PLAIN, 16));

    // LEBAR KOLOM
    TableBahan.getColumnModel().getColumn(0)
            .setPreferredWidth(50); // ID

    TableBahan.getColumnModel().getColumn(1)
            .setPreferredWidth(180); // Nama Bahan

    TableBahan.getColumnModel().getColumn(2)
            .setPreferredWidth(80); // Stok

    TableBahan.getColumnModel().getColumn(3)
            .setPreferredWidth(100); // Harga

    // RATA TENGAH ISI TABEL
    DefaultTableCellRenderer centerRenderer =
            new DefaultTableCellRenderer();

    centerRenderer.setHorizontalAlignment(
            javax.swing.SwingConstants.CENTER);

    for (int i = 0; i < TableBahan.getColumnCount(); i++) {
        TableBahan.getColumnModel()
                .getColumn(i)
                .setCellRenderer(centerRenderer);
    }

    TableBahan.getTableHeader().repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBpilihbahan = new javax.swing.JComboBox<>();
        Sjumlah = new javax.swing.JSpinner();
        TFhargasatuan = new javax.swing.JTextField();
        TFtotalharga = new javax.swing.JTextField();
        JBbelibahan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBahan = new javax.swing.JTable();
        LBsaldo = new javax.swing.JLabel();
        JBhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(196, 105, 47));

        jPanel2.setBackground(new java.awt.Color(107, 45, 15));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Pixelify Sans", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INVENTORY & SHOP");

        jPanel1.setBackground(new java.awt.Color(228, 191, 120));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 220, 163), 2));
        jPanel1.setForeground(new java.awt.Color(248, 220, 163));

        jPanel3.setBackground(new java.awt.Color(248, 220, 163));

        jLabel1.setFont(new java.awt.Font("Pixelify Sans", 1, 14)); // NOI18N
        jLabel1.setText("Pilih Bahan");

        jLabel2.setFont(new java.awt.Font("Pixelify Sans", 1, 14)); // NOI18N
        jLabel2.setText("Jumlah Beli");

        jLabel3.setFont(new java.awt.Font("Pixelify Sans", 1, 14)); // NOI18N
        jLabel3.setText("Harga Satuan");

        jLabel4.setFont(new java.awt.Font("Pixelify Sans", 1, 14)); // NOI18N
        jLabel4.setText("Total Harga");

        CBpilihbahan.setFont(new java.awt.Font("Pixelify Sans", 0, 14)); // NOI18N
        CBpilihbahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Bahan--", "Bread", "Patty", "Onion", "Egg", "Cheese", "Lettuce", "Tomato", "Salmon" }));
        CBpilihbahan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CBpilihbahan.addActionListener(this::CBpilihbahanActionPerformed);

        Sjumlah.setFont(new java.awt.Font("MS PGothic", 0, 14)); // NOI18N
        Sjumlah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sjumlah.addChangeListener(this::SjumlahStateChanged);

        TFhargasatuan.setEditable(false);
        TFhargasatuan.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        TFhargasatuan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TFtotalharga.setEditable(false);
        TFtotalharga.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        TFtotalharga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBbelibahan.setBackground(new java.awt.Color(76, 175, 80));
        JBbelibahan.setFont(new java.awt.Font("Pixelify Sans", 1, 18)); // NOI18N
        JBbelibahan.setForeground(new java.awt.Color(255, 255, 255));
        JBbelibahan.setText("BELI");
        JBbelibahan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBbelibahan.addActionListener(this::JBbelibahanActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFhargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBpilihbahan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(JBbelibahan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBpilihbahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Sjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFhargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(JBbelibahan)
                .addGap(22, 22, 22))
        );

        jLabel6.setBackground(new java.awt.Color(242, 201, 76));
        jLabel6.setFont(new java.awt.Font("Pixelify Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BELI BAHAN");
        jLabel6.setAlignmentX(1.0F);
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setIconTextGap(100);
        jLabel6.setInheritsPopupMenu(false);
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 20));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(90, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameburger/image/burger icon 1.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameburger/image/burger icon 1.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(228, 191, 120));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 220, 163), 2));

        TableBahan.setBackground(new java.awt.Color(248, 220, 163));
        TableBahan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TableBahan.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        TableBahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Bread",  new Integer(10), "150"},
                { new Integer(2), "Patty",  new Integer(4), "200"},
                { new Integer(3), "Onion",  new Integer(10), "50"},
                { new Integer(4), "Egg",  new Integer(5), "100"},
                { new Integer(5), "Cheese",  new Integer(4), "150"},
                { new Integer(6), "Lettuce",  new Integer(10), "50"},
                { new Integer(7), "Tomato",  new Integer(6), "60"},
                { new Integer(8), "Salmon",  new Integer(3), "300"}
            },
            new String [] {
                "ID", "Nama Bahan", "Stok", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableBahan.setToolTipText("");
        TableBahan.setAlignmentX(1.0F);
        TableBahan.setAlignmentY(10.0F);
        TableBahan.setGridColor(new java.awt.Color(255, 255, 255));
        TableBahan.setIntercellSpacing(new java.awt.Dimension(10, 10));
        TableBahan.setName(""); // NOI18N
        TableBahan.setRowHeight(40);
        TableBahan.setShowGrid(false);
        TableBahan.setShowHorizontalLines(true);
        TableBahan.setShowVerticalLines(true);
        jScrollPane1.setViewportView(TableBahan);

        LBsaldo.setBackground(new java.awt.Color(255, 102, 0));
        LBsaldo.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        LBsaldo.setForeground(new java.awt.Color(255, 255, 255));
        LBsaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBsaldo.setText("SALDO  : 500");
        LBsaldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LBsaldo.setOpaque(true);
        LBsaldo.setPreferredSize(new java.awt.Dimension(100, 30));

        JBhapus.setBackground(new java.awt.Color(214, 58, 44));
        JBhapus.setFont(new java.awt.Font("Pixelify Sans", 1, 12)); // NOI18N
        JBhapus.setForeground(new java.awt.Color(255, 255, 255));
        JBhapus.setText("HAPUS");
        JBhapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBhapus.setMaximumSize(new java.awt.Dimension(74, 22));
        JBhapus.setPreferredSize(new java.awt.Dimension(74, 22));
        JBhapus.addActionListener(this::JBhapusActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LBsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void loadSaldo() {
    try {
        Connection con = new KoneksiDB().getConnection();

        String sql =
                "SELECT saldo FROM shop_data WHERE id_data = 1";

        PreparedStatement ps =
                con.prepareStatement(sql);

        ResultSet rs =
                ps.executeQuery();

        if (rs.next()) {
            saldo = rs.getInt("saldo");
            LBsaldo.setText("Saldo : Rp " + saldo);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
}

    private void loadBahan() {

    DefaultTableModel model =
            (DefaultTableModel) TableBahan.getModel();

    model.setRowCount(0);

    try {

        Connection con =
                new KoneksiDB().getConnection();

        String sql =
                "SELECT * FROM bahan";

        PreparedStatement ps =
                con.prepareStatement(sql);

        ResultSet rs =
                ps.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_bahan"),
                rs.getString("nama_bahan"),
                rs.getInt("stok"),
                rs.getInt("harga")
            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
}

    private void CBpilihbahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpilihbahanActionPerformed
        // TODO add your handling code here:
        String bahan = CBpilihbahan.getSelectedItem().toString();
        int harga = 0;
        if (bahan.equals("Pilih Bahan")) {
            TFhargasatuan.setText("");
            TFtotalharga.setText("");
            return;
        }
        else if (bahan.equals("Bread")) {
            harga = 150;
        }
        else if (bahan.equals("Patty")) {
            harga = 200;
        }
        else if (bahan.equals("Onion")) {
            harga = 50;
        }
        else if (bahan.equals("Egg")) {
            harga = 100;
        }
        else if (bahan.equals("Cheese")) {
            harga = 150;
        }
        else if (bahan.equals("Lettuce")) {
            harga = 50;
        }
        else if (bahan.equals("Tomato")) {
            harga = 60;
        }
        else if (bahan.equals("Salmon")) {
            harga = 300;
        }
        TFhargasatuan.setText(String.valueOf(harga));
        int jumlah = (Integer) Sjumlah.getValue();
        int total = harga * jumlah;
        TFtotalharga.setText(String.valueOf(total));
    }//GEN-LAST:event_CBpilihbahanActionPerformed

    private void SjumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SjumlahStateChanged
        // TODO add your handling code here:
         CBpilihbahanActionPerformed(null);
    }//GEN-LAST:event_SjumlahStateChanged

    private void JBbelibahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbelibahanActionPerformed
        // TODO add your handling code here:
        String bahan = CBpilihbahan.getSelectedItem().toString();

    if (bahan.equals("Pilih Bahan")) {

        JOptionPane.showMessageDialog(this,
        "Pilih bahan terlebih dahulu!");

        return;
    }

    int jumlah = (Integer) Sjumlah.getValue();

    int harga =
    Integer.parseInt(TFhargasatuan.getText());

    int total =
    Integer.parseInt(TFtotalharga.getText());

    // cek saldo cukup atau tidak
    if (saldo < total) {

        JOptionPane.showMessageDialog(this,
        "Saldo tidak cukup!");

        return;
    }

    // kurangi saldo
    saldo -= total;

    try {

    Connection con =
            new KoneksiDB().getConnection();

    String sqlSaldo =
            "UPDATE shop_data SET saldo=? WHERE id_data=1";

    PreparedStatement psSaldo =
            con.prepareStatement(sqlSaldo);

    psSaldo.setInt(1, saldo);
    psSaldo.executeUpdate();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }

    LBsaldo.setText("Saldo : Rp " + saldo);

    DefaultTableModel model =
    (DefaultTableModel) TableBahan.getModel();

    boolean ditemukan = false;

    for (int i = 0; i < model.getRowCount(); i++) {

        String namaBahan =
        model.getValueAt(i, 1).toString();

        if (namaBahan.equals(bahan)) {

            int stokLama =
            Integer.parseInt(
            model.getValueAt(i, 2).toString());

            int stokBaru = stokLama + jumlah;

            model.setValueAt(stokBaru, i, 2);

            ditemukan = true;

            try {

            Connection con =
                    new KoneksiDB().getConnection();

            String sql =
                    "UPDATE bahan SET stok=? WHERE nama_bahan=?";

            PreparedStatement ps =
                    con.prepareStatement(sql);

            ps.setInt(1, stokBaru);
            ps.setString(2, bahan);

            ps.executeUpdate();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this,
                        e.getMessage());
            }

            break;
        }
    }

    if (!ditemukan) {

        int id = model.getRowCount() + 1;

        model.addRow(new Object[]{
            id,
            bahan,
            jumlah
        });
    }

    loadSaldo();
    loadBahan();
    JOptionPane.showMessageDialog(this,
    "Bahan berhasil dibeli!");
    }//GEN-LAST:event_JBbelibahanActionPerformed

    private void JBhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =
    (DefaultTableModel) TableBahan.getModel();

    int baris = TableBahan.getSelectedRow();

    if (baris == -1) {

        JOptionPane.showMessageDialog(this,
        "Pilih bahan terlebih dahulu!");

        return;
    }

    String bahan =
    model.getValueAt(baris, 1).toString();

    int stokLama =
    Integer.parseInt(
    model.getValueAt(baris, 2).toString());

    int harga = 0;

    // harga bahan
    if (bahan.equals("Bread")) {
        harga = 100;
    }
    else if (bahan.equals("Patty")) {
        harga = 200;
    }
    else if (bahan.equals("Onion")) {
        harga = 50;
    }
    else if (bahan.equals("Egg")) {
        harga = 100;
    }
    else if (bahan.equals("Cheese")) {
        harga = 150;
    }
    else if (bahan.equals("Lettuce")) {
        harga = 50;
    }
    else if (bahan.equals("Tomato")) {
        harga = 60;
    }
    else if (bahan.equals("Salmon")) {
        harga = 300;
    }

    // stok dikurangi 1
    int stokBaru = stokLama - 1;

    // uang kembali
    saldo += harga;

    try {

    Connection con =
            new KoneksiDB().getConnection();

    String sql =
            "UPDATE shop_data SET saldo=? WHERE id_data=1";

    PreparedStatement ps =
            con.prepareStatement(sql);

    ps.setInt(1, saldo);

    ps.executeUpdate();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }


    LBsaldo.setText("Saldo : Rp " + saldo);

    if (stokBaru > 0) {

        model.setValueAt(stokBaru, baris, 2);

    } else {

        model.removeRow(baris);
    }

    JOptionPane.showMessageDialog(this,
    "Bahan berhasil dijual!");
    }//GEN-LAST:event_JBhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventoryShopFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBpilihbahan;
    private javax.swing.JButton JBbelibahan;
    private javax.swing.JButton JBhapus;
    private javax.swing.JLabel LBsaldo;
    private javax.swing.JSpinner Sjumlah;
    private javax.swing.JTextField TFhargasatuan;
    private javax.swing.JTextField TFtotalharga;
    private javax.swing.JTable TableBahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
