
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sri Yuniarti
 */
public class Order extends javax.swing.JFrame {

    KoneksiDB kon;

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        setTitle("RECIPE BOOK");
        setIconImage(new ImageIcon(getClass().getResource("/gameburger/image/burger icon 2.png")).getImage());
        
        kon = new KoneksiDB();

        tampildata();
        loadBahan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        btnHapus = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaResep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnHapusBahan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSusunanBahan = new javax.swing.JTextArea();
        cmbBahan = new javax.swing.JComboBox<>();
        btnTambahBahan = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 18, 10));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(107, 45, 15));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(132, 70, 37)));

        jPanel4.setBackground(new java.awt.Color(107, 45, 15));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RECIPE LIST");

        jPanel5.setBackground(new java.awt.Color(70, 29, 9));

        btnRefresh.setBackground(new java.awt.Color(166, 72, 24));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRefresh.setText("REFRESH");
        btnRefresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(200, 125, 97), new java.awt.Color(235, 160, 108), new java.awt.Color(44, 16, 3), new java.awt.Color(60, 25, 5)));
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.setOpaque(true);
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapus.setText("DELETE SELECTED");
        btnHapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153), new java.awt.Color(44, 16, 3), new java.awt.Color(153, 0, 0)));
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setOpaque(true);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel6.setBackground(new java.awt.Color(70, 29, 9));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recipe Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingredients");

        btnHapusBahan.setBackground(new java.awt.Color(253, 140, 0));
        btnHapusBahan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapusBahan.setForeground(new java.awt.Color(59, 28, 2));
        btnHapusBahan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapusBahan.setText("Delete Ingredient");
        btnHapusBahan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(190, 135, 106), new java.awt.Color(254, 183, 52), new java.awt.Color(54, 20, 2), new java.awt.Color(218, 102, 16)));
        btnHapusBahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusBahan.setOpaque(true);
        btnHapusBahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusBahanMouseClicked(evt);
            }
        });

        taSusunanBahan.setEditable(false);
        taSusunanBahan.setColumns(20);
        taSusunanBahan.setRows(5);
        jScrollPane2.setViewportView(taSusunanBahan);

        cmbBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBahanActionPerformed(evt);
            }
        });

        btnTambahBahan.setBackground(new java.awt.Color(56, 141, 16));
        btnTambahBahan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTambahBahan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahBahan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTambahBahan.setText("Add");
        btnTambahBahan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(38, 62, 1), new java.awt.Color(127, 203, 55), new java.awt.Color(47, 31, 2), new java.awt.Color(25, 94, 6)));
        btnTambahBahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahBahan.setOpaque(true);
        btnTambahBahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahBahanMouseClicked(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(56, 141, 16));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSimpan.setText("SAVE NEW RECIPE");
        btnSimpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(38, 62, 1), new java.awt.Color(127, 203, 55), new java.awt.Color(47, 31, 2), new java.awt.Color(25, 94, 6)));
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setOpaque(true);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(56, 141, 16));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdate.setText("UPDATE SELECTED");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(38, 62, 1), new java.awt.Color(127, 203, 55), new java.awt.Color(47, 31, 2), new java.awt.Color(25, 94, 6)));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setOpaque(true);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbBahan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNamaResep, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHapusBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahBahan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnHapusBahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD / EDIT RESEP");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8_Go_Back_36px.png"))); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(btnBack))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampildata() {
        //        membuat header table
        Object header[] = {"id", "Recipe Name", "Ingredients"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tableData.setModel(data);

//          Query
        String queryTampil = "SELECT * FROM resep_burger";
        try {
//            mengirimkan query
            Statement st = kon.con.createStatement();
//            menyimpan hasil sementara dari database
            ResultSet rs = st.executeQuery(queryTampil);
//            memasukkan data ke tabel
            while (rs.next()) {
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom3 = rs.getString(3);
                String kolom[] = {kolom1, kolom2, kolom3};

                data.addRow(kolom);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void loadBahan() {
        try {
            // Kosongkan isi combobox terlebih dahulu agar tidak duplikat
            cmbBahan.removeAllItems();
            cmbBahan.addItem("- Pilih Bahan -"); // Placeholder opsional

            // Query untuk mengambil data bahan
            String queryBahan = "SELECT nama_bahan FROM bahan ORDER BY nama_bahan ASC";

            // Mengirimkan query menggunakan koneksi 'kon.con' milik Anda
            Statement st = kon.con.createStatement();

            // Menyimpan hasil dari database
            ResultSet rs = st.executeQuery(queryBahan);

            // Memasukkan data nama bahan satu per satu ke combobox
            while (rs.next()) {
                String namaBahan = rs.getString("nama_bahan");
                cmbBahan.addItem(namaBahan);
            }
        } catch (Exception e) {
            // Menampilkan error jika ada masalah
            System.out.println("Error loadBahan: " + e.getMessage());
        }
    }
    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        MainMenu FrameMainMenu = new MainMenu();
        FrameMainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        tampildata();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void cmbBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBahanActionPerformed

    private void btnTambahBahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBahanMouseClicked
        String bahanPilihan = cmbBahan.getSelectedItem().toString();
        String SusunanBahan = taSusunanBahan.getText();

        if (bahanPilihan.equals("- Pilih Bahan -")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih bahan terlebih dahulu!");
            return;
        }

        if (SusunanBahan.isEmpty()) {
            taSusunanBahan.setText(bahanPilihan);
        } else {
            taSusunanBahan.setText(SusunanBahan + "," + bahanPilihan);
        }
    }//GEN-LAST:event_btnTambahBahanMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        String namaResep = txtNamaResep.getText();
        String susunanBahan = taSusunanBahan.getText();

        if (namaResep.isEmpty() || susunanBahan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama resep dan susunan bahan tidak boleh kosong!");
            return;
        }

        String querySimpan = "INSERT INTO resep_burger (nama_resep, urutan_bahan) VALUES ('" + namaResep + "', '" + susunanBahan + "')";

        try {
            Statement st = kon.con.createStatement();
            st.executeUpdate(querySimpan);
            JOptionPane.showMessageDialog(null, "Data " + namaResep + " berhasil ditambahkan");

            tampildata();

            txtNamaResep.setText("");
            taSusunanBahan.setText("");

            if (cmbBahan.getItemCount() > 0) {
                cmbBahan.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan resep: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnHapusBahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusBahanMouseClicked
        String susunanBahan = taSusunanBahan.getText();

        if (susunanBahan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Susunan bahan sudah kosong!");
            return;
        }

        int komaTerakhir = susunanBahan.lastIndexOf(",");

        if (komaTerakhir == -1) {
            taSusunanBahan.setText("");
        } else {
            String teksBaru = susunanBahan.substring(0, komaTerakhir);
            taSusunanBahan.setText(teksBaru);
        }
    }//GEN-LAST:event_btnHapusBahanMouseClicked

    private String idResepTerpilih;
    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        // Mendapatkan indeks baris yang diklik
        int baris = tableData.getSelectedRow();

        // Memastikan ada baris yang valid (tidak error)
        if (baris != -1) {
            // Mengambil data dari JTable
            // Asumsi: indeks 0 = id, 1 = Nama Resep, 2 = Urutan Bahan
            idResepTerpilih = tableData.getValueAt(baris, 0).toString();
            String namaResep = tableData.getValueAt(baris, 1).toString();
            String susunanBahan = tableData.getValueAt(baris, 2).toString();

            // Memasukkan data ke TextField dan TextArea
            txtNamaResep.setText(namaResep);
            taSusunanBahan.setText(susunanBahan);
        }
    }//GEN-LAST:event_tableDataMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        String namaResepBaru = txtNamaResep.getText();
        String susunanBahanBaru = taSusunanBahan.getText();

        if (idResepTerpilih.equals("")) {
            JOptionPane.showMessageDialog(null, "Silakan pilih data dari tabel terlebih dahulu!");
            return;
        }

        if (namaResepBaru.isEmpty() || susunanBahanBaru.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama resep dan susunan bahan tidak boleh kosong!");
            return;
        }

        String queryUpdate = "UPDATE resep_burger SET nama_resep = '" + namaResepBaru
                + "', urutan_bahan = '" + susunanBahanBaru
                + "' WHERE id = '" + idResepTerpilih + "'";

        try {
            Statement st = kon.con.createStatement();
            st.executeUpdate(queryUpdate);
            JOptionPane.showMessageDialog(null, "Data resep berhasil diperbarui!");

            tampildata();

            txtNamaResep.setText("");
            taSusunanBahan.setText("");
            idResepTerpilih = "";

        } catch (Exception e) {
            System.out.println("Error saat update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        if (idResepTerpilih.equals("")) {
            JOptionPane.showMessageDialog(null, "Silakan pilih data dari tabel yang ingin dihapus terlebih dahulu!");
            return;
        }

        // munculkan dialog konfirmasi sebelum menghapus
        int konfirmasi = JOptionPane.showConfirmDialog(null,
            "Apakah Anda yakin ingin menghapus resep ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        // mengecek pilihan user
        if (konfirmasi == JOptionPane.YES_OPTION) {

            String queryHapus = "DELETE FROM resep_burger WHERE id = '" + idResepTerpilih + "'";

            try {
                Statement st = kon.con.createStatement();
                st.executeUpdate(queryHapus);

                JOptionPane.showMessageDialog(null, "Data resep berhasil dihapus!");

                tampildata();

                txtNamaResep.setText("");
                taSusunanBahan.setText("");
                idResepTerpilih = "";

                if (cmbBahan.getItemCount() > 0) {
                    cmbBahan.setSelectedIndex(0);
                }

            } catch (Exception e) {
                System.out.println("Error saat menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnHapusBahan;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JLabel btnTambahBahan;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JComboBox<String> cmbBahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taSusunanBahan;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtNamaResep;
    // End of variables declaration//GEN-END:variables
}
